//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Default {
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// GlobalEvents control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents GlobalEvents;
    
    /// <summary>
    /// ProgressControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ASPxProgressControl ProgressControl;
    
    /// <summary>
    /// LogoLink control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink LogoLink;
    
    /// <summary>
    /// themedImageControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ThemedImageControl themedImageControl;
    
    /// <summary>
    /// SecurityActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder SecurityActionContainer;
    
    /// <summary>
    /// NavigationTabsActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationTabsActionContainer NavigationTabsActionContainer;
    
    /// <summary>
    /// Splitter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxSplitter.ASPxSplitter Splitter;
    
    /// <summary>
    /// SplitterContentControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxSplitter.SplitterContentControl SplitterContentControl1;
    
    /// <summary>
    /// VerticalToolsActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder VerticalToolsActionContainer;
    
    /// <summary>
    /// DiagnosticActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder DiagnosticActionContainer;
    
    /// <summary>
    /// SplitterContentControl3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxSplitter.SplitterContentControl SplitterContentControl3;
    
    /// <summary>
    /// ToolBar control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder ToolBar;
    
    /// <summary>
    /// viewImageControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ViewImageControl viewImageControl;
    
    /// <summary>
    /// viewCaptionControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ViewCaptionControl viewCaptionControl;
    
    /// <summary>
    /// ViewsHistoryNavigationContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer ViewsHistoryNavigationContainer;
    
    /// <summary>
    /// RecordsNavigationContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder RecordsNavigationContainer;
    
    /// <summary>
    /// EditModeActions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder EditModeActions;
    
    /// <summary>
    /// ErrorInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl ErrorInfo;
    
    /// <summary>
    /// viewSiteControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.ViewSiteControl viewSiteControl;
    
    /// <summary>
    /// EditModeActions2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder EditModeActions2;
    
    /// <summary>
    /// QuickAccessNavigationActionContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer QuickAccessNavigationActionContainer;
    
    /// <summary>
    /// InfoMessagesPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal InfoMessagesPanel;
    
    /// <summary>
    /// aboutInfoControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.ExpressApp.Web.Controls.AboutInfoControl aboutInfoControl;
}
