'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class [Default]

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' GlobalEvents control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected GlobalEvents As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

	''' <summary>
	''' ProgressControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

	''' <summary>
	''' LogoLink control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected LogoLink As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' ThemedImageControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected themedImageControl As Global.DevExpress.ExpressApp.Web.Controls.ThemedImageControl

	''' <summary>
	''' SecurityActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SecurityActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' NavigationTabsActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected NavigationTabsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationTabsActionContainer

	''' <summary>
	''' Splitter control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Splitter As Global.DevExpress.Web.ASPxSplitter.ASPxSplitter

	''' <summary>
	''' SplitterContentControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SplitterContentControl1 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' VerticalToolsActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected VerticalToolsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' DiagnosticActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' SplitterContentControl3 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SplitterContentControl3 As Global.DevExpress.Web.ASPxSplitter.SplitterContentControl

	''' <summary>
	''' ToolBar control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ToolBar As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' ViewImageControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected viewImageControl As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

	''' <summary>
	''' ViewCaptionControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected viewCaptionControl As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

	''' <summary>
	''' ViewsHistoryNavigationContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewsHistoryNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

	''' <summary>
	''' RecordsNavigationContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected RecordsNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' EditModeActions control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected EditModeActions As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' ErrorInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	''' <summary>
	''' ViewSiteControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
    Protected viewSiteControl1 As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

	''' <summary>
	''' EditModeActions2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected EditModeActions2 As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' QuickAccessNavigationActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected QuickAccessNavigationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer

	''' <summary>
	''' InfoMessagesPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' AboutInfoControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected aboutInfoControl As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
End Class
