'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' DefaultVertical class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class DefaultVertical

    ''' <summary>
    ''' ProgressControl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

    ''' <summary>
    ''' form1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    ''' <summary>
    ''' LogoLink control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LogoLink As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' LogoImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LogoImage As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' SecurityActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SecurityActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' VerticalNewActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected VerticalNewActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' SearchActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' NavigationBarActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected NavigationBarActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer

    ''' <summary>
    ''' ToolsRoundPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ToolsRoundPanel As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

    ''' <summary>
    ''' PanelContent1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PanelContent1 As Global.DevExpress.Web.ASPxRoundPanel.PanelContent

    ''' <summary>
    ''' VerticalToolsActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected VerticalToolsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ViewsHistoryNavigationContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewsHistoryNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

    ''' <summary>
    ''' ViewImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewImage As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' ViewCaptionLabel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewCaptionLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' ToolBar control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ToolBar As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    ''' <summary>
    ''' ContextObjectsCreationActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' TopRecordEditActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TopRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' RecordsNavigationContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RecordsNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ViewPresentationActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewPresentationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ListViewDataManagementActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ListViewDataManagementActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ErrorInfo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    ''' <summary>
    ''' Table1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Table1 As Global.System.Web.UI.WebControls.Table

    ''' <summary>
    ''' TableRow2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow

    ''' <summary>
    ''' ViewSite control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewSite As Global.System.Web.UI.WebControls.TableCell

    ''' <summary>
    ''' NavigationLinksActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected NavigationLinksActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationLinksActionContainer

    ''' <summary>
    ''' Copyright control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Copyright As Global.System.Web.UI.WebControls.Literal

    ''' <summary>
    ''' DiagnosticActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' InfoMessagesPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal
End Class
