'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Default class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class [Default]

    '''<summary>
    '''ProgressControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LogoLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LogoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SecurityActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecurityActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''NavigationTabsActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavigationTabsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationTabsActionContainer

    '''<summary>
    '''VerticalNewActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerticalNewActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''SearchActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''ToolsRoundPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolsRoundPanel As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''VerticalToolsActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerticalToolsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''ViewsHistoryNavigationContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewsHistoryNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

    '''<summary>
    '''ViewImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ViewCaptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewCaptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBar As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''ContextObjectsCreationActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''TopRecordEditActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TopRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''RecordsNavigationContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecordsNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''ViewPresentationActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewPresentationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''ListViewDataManagementActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListViewDataManagementActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    '''<summary>
    '''ErrorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''ViewSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSite As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''NavigationLinksActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NavigationLinksActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationLinksActionContainer

    '''<summary>
    '''ApplicationTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplicationTitle As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''InfoMessagesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Copyright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Copyright As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DiagnosticActionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer
End Class
