'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' DialogPage class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class DialogPage

    ''' <summary>
    ''' ProgressControl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

    ''' <summary>
    ''' form1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    ''' <summary>
    ''' ViewImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewImage As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' ViewCaptionLabel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewCaptionLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' ErrorInfo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    ''' <summary>
    ''' Table1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Table1 As Global.System.Web.UI.WebControls.Table

    ''' <summary>
    ''' TableRow5 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableRow5 As Global.System.Web.UI.WebControls.TableRow

    ''' <summary>
    ''' TableCell1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableCell1 As Global.System.Web.UI.WebControls.TableCell

    ''' <summary>
    ''' SearchActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' TableRow2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow

    ''' <summary>
    ''' ViewSite control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewSite As Global.System.Web.UI.WebControls.TableCell

    ''' <summary>
    ''' TableRow3 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableRow3 As Global.System.Web.UI.WebControls.TableRow

    ''' <summary>
    ''' TableCell4 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected TableCell4 As Global.System.Web.UI.WebControls.TableCell

    ''' <summary>
    ''' ObjectsCreationActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' PopupActions control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PopupActions As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' DiagnosticActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer
End Class
