'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' NestedFrameControl class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class NestedFrameControl

    ''' <summary>
    ''' ContextObjectsCreationActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' RecordEditContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RecordEditContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ViewContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' DiagnosticActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' FiltersActionContainer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected FiltersActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WebActionContainer

    ''' <summary>
    ''' ViewImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewImage As Global.System.Web.UI.WebControls.Image

    ''' <summary>
    ''' ViewCaptionLabel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewCaptionLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' ViewSite control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ViewSite As Global.System.Web.UI.WebControls.Panel
End Class
