'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class NestedFrameControl

	''' <summary>
	''' ToolBar control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ToolBar As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As Global.System.Web.UI.WebControls.Panel

	''' <summary>
	''' ViewImage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewImage As Global.System.Web.UI.WebControls.Image

	''' <summary>
	''' ViewCaptionLabel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewCaptionLabel As Global.System.Web.UI.WebControls.Label
End Class
